{% set version = "1.3.0" %}

package:
  name: qtawesome
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/q/qtawesome/QtAwesome-{{ version }}.tar.gz
  sha256: 104ed030e2c2237606898a621e8b2dc3f0a64c753a54d7bd6fa0015345fb1ad2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - qtpy

test:
  requires:
    - pyqt
  imports:
    - qtawesome

about:
  home: https://github.com/spyder-ide/qtawesome
  license: MIT
  license_file: LICENSE.txt
  summary: Iconic fonts in PyQt and PySide applications

extra:
  recipe-maintainers:
    - SylvainCorlay
    - ccordoba12
    - dalthviz
