{% set version = "1.4.0" %}

package:
  name: qtawesome
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/q/qtawesome/qtawesome-{{ version }}.tar.gz
  sha256: 783e414d1317f3e978bf67ea8e8a1b1498bad9dbd305dec814027e3b50521be6

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - qta-browser = qtawesome.icon_browser:run
    - qta-install-fonts-all-users = qtawesome:install_bundled_fonts_system_wide

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - qtpy

test:
  requires:
    - pyqt
    - python {{ python_min }}
  imports:
    - qtawesome

about:
  home: https://github.com/spyder-ide/qtawesome
  license: MIT
  license_file: LICENSE.txt
  summary: Iconic fonts in PyQt and PySide applications

extra:
  recipe-maintainers:
    - SylvainCorlay
    - ccordoba12
    - dalthviz
