{% set version = "1.3.1" %}

package:
  name: qtawesome
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/q/qtawesome/QtAwesome-{{ version }}.tar.gz
  sha256: 075b2c9ee01cbaf5e3a4bebed0e5529ee8605981355f21dea051b15c1b869e1b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - qtpy

test:
  requires:
    - pyqt
    - python {{ python_min }}
  imports:
    - qtawesome

about:
  home: https://github.com/spyder-ide/qtawesome
  license: MIT
  license_file: LICENSE.txt
  summary: Iconic fonts in PyQt and PySide applications

extra:
  recipe-maintainers:
    - SylvainCorlay
    - ccordoba12
    - dalthviz
