# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Smqa+pNNzzzpehABC+R2ve6tOAGPw6rS2ET4HKiEgD3Z8+yAY4ECYcP8RwGmUtPlEC72Ra3SWNm8nRg67GlX+v/qtctTOSL/tQnPK8aohr8TiGGn90XLvt4C3JnJr7CTwXO/xHoH8r+a7yEDcsT0JW+c2HOvrKGfedFrI3N79qaWLg4YYxIo7ZCiqcywg5rry1UD3FmB8sheKoyVB7U8ATRhv8sh41Wlb4y2oxAmhMyoGsbQw8sc+j6iFDloZSznmDQBMBadbRdcNHmwzQPj1ZgMp7QmqjvZHYuJ79Rjc+raKCA9i6u/DFa5HPgRZUmVwpphjZeOcSWf18Q5DbAxwkibZVdIa6rlTj8KyoyI9jIXZsxJPj2rsKx81Fkgr5Ywj6Y9OBNSOQEP+wc+C31UusSUHOGGF946/iHm3KZpS+rQCcrS3id7Ry1HJbd7U5sh4ackrJoIreCJavwyUPa7883VEEXcDQC4I+OzO7uSK098TIT8JxOOn7/V6N2JarYS4sZ6e2+2+4AAFWS/cy4at9anx0oP7jVCGBwO/tnVeZtTopdZtVLpkT7WlLtfbtG5v8H1AeBDQLOsw9gsD+N78CkvKWiEpfVbLerw2H1oJxZgb/MslhAdOE19l9fgyhSBjYYrO1DLiTr/ScRtHv4pf6jD1wpFUvN+xCbqe9Fx38k="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
